print("Bienvenido al cajero automático")
print("Por favor, ingrese su número de cuenta:")
numero_cuenta = input()
print("Por favor, ingrese su PIN:")
pin = input()
print("Seleccione una opción:")
print("1. Consultar saldo")
print("2. Retirar efectivo")
print("3. Depositar efectivo")
opcion = input()